# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: "3.10"
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install flake8 pytest
  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  #   - name: Lint with flake8
  #     run: |
  #       # stop the build if there are Python syntax errors or undefined names
  #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  #       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  #       flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  #   - name: Test with pytest
  #     env:
  #       MONGO_URL: ${{ secrets.MONGO_URL }}
  #     run: |
  #       pytest
  #   - name: Build & push Docker image
  #     uses: mr-smithers-excellent/docker-build-push@v5
  #     with:
  #       image: sotalvaroo/oldwave-fastapi-backend
  #       tags: latest
  #       registry: docker.io
  #       dockerfile: Dockerfile  
  #       buildArgs: MONGO_URL=${{ secrets.MONGO_URL }}
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}

  Deploy:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2 
        - name: Deploy in EC2
          env:
              PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
              HOSTNAME : ec2-3-84-235-83.compute-1.amazonaws.com
              USER_NAME : ubuntu
              
          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

    # - name: Deploy to Heroku
    #   uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key:  ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: "oldwave-fastapi-backend"
    #     heroku_email: "santiago.otalvaroo@udea.edu.co"
    #     #healthcheck: "https://oldwave-fastapi-backend.herokuapp.com/healthcheck"
    #     rollbackonhealthcheckfailed: true
